
#define SIZEOF_INT 4
#define _STLP_UINT32_T unsigned int
#define _STLP_NO_PARTIAL_SPECIALIZATION_SYNTAX 1
#define _STLP_LONG_LONG 1
#define _STLP_NEED_TYPENAME 1
#define _STLP_HAS_NO_NEW_C_HEADERS 1
#define _STLP_NO_NEW_STYLE_HEADERS 1
#define _STLP_NO_MEMBER_TEMPLATES 1
#define _STLP_NO_FRIEND_TEMPLATES 1
#define _STLP_NO_QUALIFIED_FRIENDS 1
#define _STLP_NO_MEMBER_TEMPLATE_KEYWORD 1
#define _STLP_NO_MEMBER_TEMPLATE_CLASSES 1
#define _STLP_NO_CLASS_PARTIAL_SPECIALIZATION 1
#define _STLP_NO_FUNCTION_TMPL_PARTIAL_ORDER 1
#define _STLP_LIMITED_DEFAULT_TEMPLATES 1
#define _STLP_NO_DEFAULT_NON_TYPE_PARAM 1
#define _STLP_NON_TYPE_TMPL_PARAM_BUG 1
#define _STLP_NO_STRING_HEADER 1
#define _STLP_HAS_NO_NEW_IOSTREAMS 1
#define _STLP_NO_NEW_IOSTREAMS 1
#define _STLP_NO_EXCEPTION_HEADER 1
#define _STLP_DEFAULT_CONSTRUCTOR_BUG 1
#define _STLP_NO_EXPLICIT_FUNCTION_TMPL_ARGS 1
#define _STLP_NONTEMPL_BASE_MATCH_BUG 1
#define _STLP_NO_ARROW_OPERATOR 1
#define _STLP_NO_BAD_ALLOC 1
// __WATCOMC__ = 1220
#define _STLP_USE_DEFALLOC 1
#define __AUTO_CONFIGURED 1
